name: Cypress Tests

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout front-end repository
      uses: actions/checkout@v2

    - name: Checkout back-end repository
      uses: actions/checkout@v2
      with:
        repository: Horos20/rest-api-crud-nodejs
        ref: master
        path: rest-api-crud-nodejs

    - name: Install dependencies
      run: |
        cd ../rest-api-crud-nodejs && npm install
        cd ../rest-api-crud-operations && npm install

    - name: Wait for the database to start
      run: |
        npx wait-on tcp:localhost:5432 -t 30000

    - name: Create database schema and data
      run: |
        cd ./rest-api-crud-nodejs && npx prisma migrate dev

    - name: Start the backend API
      run: |
        cd ./rest-api-crud-nodejs && npm start &

    - name: Wait for the backend API to start
      run: |
        npx wait-on http://localhost:8080

    - name: Start the frontend
      run: |
        npm start &

    - name: Run Cypress tests
      run: |
        npm test